# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21932da38c9bfdc4f17c0191316177f275ce4dd1c785f61214adf80807bc680372b68f4de93bedde83cbd2389fcc1d5940074340060fc7dabc97627285f10ad8

test:
  secret_key_base: 94ccb4a06ed551f7bff0395acad12f090b4100529902ca34dadf68399369c719f9fc0942a4dfdba61810c28ca7d3bb53d877714f741c70d8287f5e7202d4947f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
